# Generated by Django 3.0.7 on 2025-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
