# Generated by Django 3.0.7 on 2025-01-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0012_customer_customer_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
