# Generated by Django 3.0.7 on 2025-01-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0013_invoice_invoice_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
    ]
