# Generated by Django 3.0.7 on 2025-01-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0014_remove_product_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_rate_with_gst',
            new_name='product_rate_without_gst',
        ),
    ]
