# Generated by Django 3.0.7 on 2025-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0015_auto_20250117_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
