# Generated by Django 3.0.7 on 2025-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0016_userprofile_business_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_bank_details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
